# Generated by Django 4.2.3 on 2023-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_log', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default="<class 'progress_log.models.Topic'>", max_length=200),
        ),
    ]
