# Generated by Django 4.2.3 on 2023-08-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_log', '0003_entry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_log.topic')),
            ],
        ),
    ]
