# Generated by Django 4.2.3 on 2023-08-08 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress_log', '0004_abouttopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttopic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Topic', max_length=200),
        ),
    ]
