# Generated by Django 4.2.3 on 2023-08-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_log', '0011_abouttopic_title_entry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouttopic',
            options={'verbose_name_plural': 'about_topics'},
        ),
    ]
